# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.forward_port 4243, 4243
    
    config.vm.provision :shell, :inline => "apt-get update; apt-get install -y puppet"

    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file  = "provision.pp"
        puppet.module_path = "puppet/modules"
    end
end
