name         'echocat-mongodb'
version      '2.0.1'
source       'git clone https://github.com/echocat/puppet-mongodb.git'
author       'echocat / Daniel Werdermann'
license      'Mozilla Public License Version 2.0'
summary      'MongoDB module with sharding'
description  'Install, enable and configure the mongod and mongos. Optional with sharding.'
project_page 'https://github.com/echocat/puppet-mongodb'
dependency   'puppetlabs/stdlib', '>= 2.2.1'
dependency   'puppetlabs/apt', '>= 1.1.0'
