name 'tmont-rethinkdb'
version '0.0.1'
source 'https://github.com/tmont/puppet-rethinkdb'
author 'tmont'
license 'MIT'
summary 'Puppet RethinkDB management module'
description 'This module can be used for basic RethinkDB installation and management'
project_page 'https://github.com/tmont/puppet-rethinkdb'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'puppetlabs/apt', '>= 1.1.0'
